### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by DavidKabelitz** [jrrdnx/craft-helpdesk-support#2]
Hi, first of all good job - love the integration.

Are there any plans to create translations for the plugin? Or with a language file? Cause right now Craft translation do not work.

Thx

**Comment by jrrdnx** [comment]
I don't currently have any plans for translations, but I can make the necessary updates to allow for them!

I also don't have the ability to provide the actual translations for any other languages, so if you have a particular language you'd like me to add support for and can provide any examples I would greatly appreciate it!

**Comment by DavidKabelitz** [comment]
Sure we would like to have German as translation, so if you can provide me a list of all strings we can translate it for you.

**Comment by jrrdnx** [comment]
@DavidKabelitz Just released 1.2.0 which includes support for language translations. A list of all current translations can be found in [/src/translations/en/helpdesk-support.php](https://github.com/jrrdnx/craft-helpdesk-support/blob/master/src/translations/en/helpdesk-support.php)

Let me know if you have any questions!

**Comment by DavidKabelitz** [comment]
That is awesome. Thanks a lot!

**Comment by DavidKabelitz** [comment]
Hi, after updating the whole page is down. Got an error:

PHP Warning – yii\base\ErrorException
The use statement with non-compound name 'Craft' has no effect

in  in /var/www/craft/vendor/jrrdnx/helpdesk-support/src/translations/en/helpdesk-support.php
line 11

**Comment by jrrdnx** [comment]
Hey @DavidKabelitz 

I'm unable to reproduce that error, but I've made a couple additional changes that should fix some Composer 2 compatibility issues. Can you try updating to [1.2.1](https://github.com/jrrdnx/craft-helpdesk-support/releases/tag/1.2.1) for me and let me know how it goes?

**Comment by DavidKabelitz** [comment]
All fine now, thx

**Comment by ghost** [comment]
Hi @jrrdnx, 
we have another Exception when calling command `./craft migrate/all`. Can you take a look at it?
```
Call Craft CLI...

Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: craft\console\Request::getHostInfo()'


in /var/www/craft/vendor/yiisoft/yii2/base/Component.php:300


Stack trace:

#0 /var/www/craft/vendor/jrrdnx/helpdesk-support/src/translations/en/helpdesk-support.php(72): yii\base\Component->__call('getHostInfo', Array)

#1 /var/www/craft/vendor/yiisoft/yii2/i18n/PhpMessageSource.php(156): include('/var/www/craft/...')

#2 /var/www/craft/vendor/craftcms/cms/src/i18n/PhpMessageSource.php(46): yii\i18n\PhpMessageSource->loadMessagesFromFile('/var/www/craft/...')
```

**Comment by jrrdnx** [comment]
@hoangngt I may have been trying to get too fancy there. I've removed the call to `getHostInfo()` in the [1.2.2](https://github.com/jrrdnx/craft-helpdesk-support/releases/tag/1.2.2) release. Give that a shot and let me know if you have any further issues.

**Comment by ghost** [comment]
@jrrdnx awesome, thanks so much for your speedy support. All good now.
